from pydantic import BaseModel


class ExperienceItem(BaseModel):
    company: str
    position: str
    date_range: str
    bullets: list[str]


class EducationItem(BaseModel):
    institution: str
    degree: str
    date_range: str


class PersonalProjectItem(BaseModel):
    name: str
    description: str
    technologies: str
    url: str = ""
    highlights: list[str]


class TechnicalSkills(BaseModel):
    ai_data: str = ""
    languages_frameworks: str = ""
    data_infrastructure: str = ""
    cloud_devops: str = ""
    testing_practices: str = ""
    ai_safety: str = ""


class SectionLabels(BaseModel):
    professional_summary: str
    technical_skills: str
    ai_data: str
    languages_frameworks: str
    data_infrastructure: str
    cloud_devops: str
    testing_practices: str
    ai_safety: str
    professional_experience: str
    personal_projects: str
    education_and_languages: str
    languages: str
    keywords: str


class ResumeData(BaseModel):
    """Structured resume data generated by the AI agent."""

    full_name: str
    title: str
    email: str = ""
    github_url: str = ""
    linkedin_url: str = ""
    professional_summary: str
    technical_skills: TechnicalSkills
    experience: list[ExperienceItem]
    education: list[EducationItem]
    languages: list[str] = []
    personal_projects: list[PersonalProjectItem] = []
    seo_keywords: str = ""
    section_labels: SectionLabels | None = None
